# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import sqlite3
import sys
import urllib.parse
from pathlib import Path

import wasabi_inventory as inv


DEFAULT_OUT = Path(".tmp") / "wasabi_stage_sample.sql"
DEFAULT_MANIFEST = Path(".tmp") / "wasabi_inventory.json"


def sql_str(value: object) -> str:
    return "'" + str(value if value is not None else "").replace("'", "''") + "'"


def source_group_for_key(key: str) -> str:
    if key.startswith("referrals/codes/"):
        return "referral_code"
    if key.endswith("/users.json"):
        return "member_user"
    if key.endswith("/orders.json"):
        return "legacy_order"
    return "unknown"


def load_manifest(path: Path) -> dict[str, dict[str, object]]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return {str(obj["key"]): obj for obj in data.get("objects", [])}


def get_json(config: dict[str, str], key: str) -> object:
    raw = inv.request_s3(config, "GET", "/" + urllib.parse.quote(key, safe="/"), {})
    return json.loads(raw.decode("utf-8-sig"))


def object_insert(key: str, group: str, raw_json: object, meta: dict[str, object], imported_at: str) -> str:
    raw_text = json.dumps(raw_json, ensure_ascii=False, separators=(",", ":"))
    return (
        "INSERT OR REPLACE INTO wasabi_import_objects "
        "(object_key, source_group, size, last_modified, sha256, imported_at) VALUES "
        f"({sql_str(key)}, {sql_str(group)}, {int(meta.get('size') or len(raw_text.encode('utf-8')))}, "
        f"{sql_str(meta.get('last_modified') or '')}, {sql_str(hashlib.sha256(raw_text.encode('utf-8')).hexdigest())}, "
        f"{sql_str(imported_at)});"
    )


def record_insert(record_id: str, object_key: str, group: str, source_id: str, record: object, imported_at: str, note: str = "") -> str:
    record_json = json.dumps(record, ensure_ascii=False, separators=(",", ":"))
    return (
        "INSERT OR REPLACE INTO wasabi_import_records "
        "(id, object_key, source_group, source_id, record_json, mapped_table, mapped_key, status, note, imported_at) VALUES "
        f"({sql_str(record_id)}, {sql_str(object_key)}, {sql_str(group)}, {sql_str(source_id)}, "
        f"{sql_str(record_json)}, '', '', 'staged', {sql_str(note)}, {sql_str(imported_at)});"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a tiny Wasabi-to-D1 staging SQL sample.")
    parser.add_argument("--docx", default=inv.DEFAULT_DOCX)
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--referrals", type=int, default=5)
    parser.add_argument("--users", type=int, default=5)
    parser.add_argument("--orders", type=int, default=3)
    args = parser.parse_args()

    config = inv.merge_config(inv.config_from_env(), inv.config_from_docx(args.docx))
    manifest = load_manifest(Path(args.manifest))
    now = dt.datetime.now(dt.timezone.utc).isoformat()

    referral_keys = [key for key in manifest if key.startswith("referrals/codes/")][: args.referrals]
    fixed_keys = [
        "shops/action/high-risk/users.json",
        "shops/action/high-risk/orders.json",
    ]
    keys = referral_keys + fixed_keys

    sql: list[str] = [
        "-- Generated by scripts/wasabi_stage_sample.py",
        "-- Staging-only import. Does not write production TravelKeeper tables.",
        "PRAGMA foreign_keys = ON;",
    ]
    summary: list[dict[str, object]] = []

    for key in keys:
        data = get_json(config, key)
        group = source_group_for_key(key)
        sql.append(object_insert(key, group, data, manifest.get(key, {}), now))
        if group == "referral_code":
            source_id = str(data.get("ref_code") or Path(key).stem) if isinstance(data, dict) else Path(key).stem
            rid = f"referral:{source_id}"
            sql.append(record_insert(rid, key, group, source_id, data, now, "sample referral code"))
            summary.append({"group": group, "key": key, "records": 1})
        elif group == "member_user" and isinstance(data, list):
            count = 0
            for idx, row in enumerate(data[: args.users]):
                source_id = ""
                if isinstance(row, dict):
                    nested = row.get("data") if isinstance(row.get("data"), dict) else row
                    source_id = str(nested.get("userId") or row.get("key") or idx)
                rid = "member_user:" + hashlib.sha1((key + ":" + source_id).encode("utf-8")).hexdigest()
                sql.append(record_insert(rid, key, group, source_id, row, now, "sample member/user"))
                count += 1
            summary.append({"group": group, "key": key, "records": count})
        elif group == "legacy_order" and isinstance(data, list):
            count = 0
            for idx, row in enumerate(data[: args.orders]):
                source_id = str(row.get("orderId") or idx) if isinstance(row, dict) else str(idx)
                rid = "legacy_order:" + hashlib.sha1((key + ":" + source_id).encode("utf-8")).hexdigest()
                sql.append(record_insert(rid, key, group, source_id, row, now, "sample legacy order; not mapped to TravelKeeper orders"))
                count += 1
            summary.append({"group": group, "key": key, "records": count})

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(sql) + "\n", encoding="utf-8")
    print(json.dumps({"success": True, "out": str(out), "summary": summary}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
